apiVersion: apps/v1beta1
kind: Deployment
metadata:
  initializers:
    pending: []
  labels:
    app: image-label-initializer
  name: image-label-initializer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: image-label-initializer
      name: image-label-initializer
    spec:
      containers:
